# Generated by Django 5.2.9 on 2025-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('current_price', models.FloatField()),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
