# Generated by Django 5.2.9 on 2025-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='formatted_price',
            field=models.CharField(default='0.00', max_length=50),
        ),
    ]
